### PR TITLE
Add an "Align.NONE" enum member.

### PR DESCRIPTION
**Pull request by smurfix**
This option means "leave me alone".
It is necessary for placing text on its baseline.

### CODE REVIEW

**Comment by gumyr** [comment]
A few lines of unittests are required - patch coverage should be 100%.

**Comment by gumyr** [comment]
Oh, how about changing `elif self.align[i] == Align.NONE:` to `elif self.align[i] == Align.NONE or self.align[i] is None:`?

**Comment by smurfix** [comment]
I can do that. However … having the same set of tests in no less than five different locations is a red flag. Time to refactor that instead of adding more repetitive code (and tests for it).

Ideas for a good function name? I tend towards `align_offset(min: Tuple[float], max: Tuple[float], align: Tuple[Align]|Align|None) -> VectorLike`.

**Comment by gumyr** [comment]
What are you proposing to change?

**Comment by smurfix** [comment]
> What are you proposing to change?

This code
```
            align_offset=[]
            for i in however_many_axes:
                if align[i] == Align.MIN:
                    align_offset.append(min_coord()[i])
                elif align[i] == Align.CENTER:
                    align_offset.append((min_coord()[i]+max_coord()[i])/2)
                elif align[i] == Align.MAX:
                    align_offset.append(max_coord()[i])
                elif align[i] == Align.NONE:
                    align_offset.append(0)
                # note no check for any other value
```
appears five times in build123d's codebase. That's four times too many. Also I'd like to calculate the coordinates once each instead of up to three times, plus I don't like to rely on typechecking to prevent results like the one you get if you `align=(None,Align.MAX)`.

**Comment by gumyr** [comment]
Sure, that code could be improved. There is an related issue https://github.com/gumyr/build123d/issues/457 - are you planning on fixing this too?

**Comment by smurfix** [comment]
Thanks for the pointer. Yes.

**Comment by gumyr** [comment]
This change was completed in PR #782

**Pull request closed without merging**
