### PR TITLE
Added Shell.loft

### PR DESCRIPTION
**Pull request by Jojain**
I also wanted to add the shell loft into the shell operations but that is rather involved to make it work in `BuildPart`
I think for it to work we would need to be able to have a list of available `Wire` in the `BuildPart` context, which currently arent stored.

It wouldn't be has difficult for the algebra api part.

### CODE REVIEW

**Comment by Jojain** [comment]
When running black latest it changes existing formatting is the version to use pinned somewhere? Or do I need to do something special to get the correct formatting?

**Comment by Jojain** [comment]
Ok so I've found what was the issue, my black was setup to line per char = 100, the default is 88.
I would still like that you provide somewhere a config to run black with so I don't have to modify my settings to contribute.

**Comment by jdegenstein** [comment]
@Jojain the defaults to use black ARE setup in pyproject.toml, including the 88 char setting you mentioned

We haven't settled on a stable black version to use, so for now the newest is fine.

**Comment by Jojain** [comment]
> @Jojain the defaults to use black ARE setup in pyproject.toml, including the 88 char setting you mentioned
> 
> We haven't settled on a stable black version to use, so for now the newest is fine.

You are right, I think I got confused, because I had a pyproject toml without it. But I think it was before I update everything. 
Anyway idk, sorry for the request then !

**Comment by gumyr** [comment]
Thank you - loft is better than it ever was!

**Pull request merged**
