### PR TITLE
Add a Rotate method to Plane

### PR DESCRIPTION
**Pull request by jdegenstein**
Please review this as I am really not sure I did everything correctly. I am particularly unsure about returning self and the function annotation.

```
In [2]: a=Plane.XY

In [3]: a
Out[3]: Plane(o=(0.00, 0.00, 0.00), x=(1.00, 0.00, 0.00), z=(0.00, 0.00, 1.00))

In [4]: a.rotate((0,90,0))
Out[4]: Plane(o=(0.00, 0.00, 0.00), x=(0.00, 0.00, -1.00), z=(1.00, 0.00, 0.00))

In [5]: a
Out[5]: Plane(o=(0.00, 0.00, 0.00), x=(0.00, 0.00, -1.00), z=(1.00, 0.00, 0.00))

In [6]: Plane.XY.rotate((0,90,0))
Out[6]: Plane(o=(0.00, 0.00, 0.00), x=(0.00, 0.00, -1.00), z=(1.00, 0.00, 0.00))
```

### CODE REVIEW

**Comment by bernhard-42** [comment]
Isn't that the same as `a = a.rotated(0, 90, 0)` which already exists?

**Comment by jdegenstein** [comment]
Yes, it is the same as that, I discussed with gumyr and he seemed open to adding this (similar to what is in CQ). There may be a way of adding with fewer lines of code.

**Comment by gumyr** [comment]
@jdegenstein, the code here is how I've been doing rotate but @bernhard-42 has a better way - here is his code from `Location.__init__`:
```py
            if isinstance(args[0], (Vector, tuple)):
                if isinstance(args[1], (Vector, tuple)):
                    rotation = [radians(a) for a in args[1]]
                    q = gp_Quaternion()
                    q.SetEulerAngles(gp_EulerSequence.gp_Intrinsic_XYZ, *rotation)
                    transform.SetRotation(q)
                elif isinstance(args[0], (Vector, tuple)) and isinstance(
                    args[1], (int, float)
                ):
                    angle = radians(args[1])
                    q = gp_Quaternion()
                    q.SetEulerAngles(gp_EulerSequence.gp_Intrinsic_XYZ, 0, 0, angle)
                    transform.SetRotation(q)

                # set translation part after setting rotation (if exists)
                transform.SetTranslationPart(Vector(args[0]).wrapped)
```
I think we should be consistent here and use this the gp_Quaternion solution with Intrinsic angles in both `Plane.rotate` and `Plane.rotated` - @bernhard-42 do you agree?

**Comment by bernhard-42** [comment]
While Euler angles are often easier to read when used in `__repl__`, for the location calculations I usually use quaternions.
And, I like when the creation of the object and printing the object uses related methods (here `SetEulerAngles`and `GetEulerAngles`) This usually avoids to introduce misinterpretations.
So, yes, I personally would go quaternions

**Pull request closed without merging**
