### PR TITLE
Update documentation for pack function

### PR DESCRIPTION
**Pull request by roman-dvorak**
Hi,
As I mentioned, I tried to expand the documentation by including documentation of the `pack` function.

### CODE REVIEW

**Comment by gumyr** [comment]
One minor typo: "If you place the arranged objects into a ``Compose``, you can easily determine their bounding box and check whether the objects fit on your print bed." - it should be `Compound` not `Compose`.

What do you think about putting most of this documentation into the `pack` docstring instead of the documentation?  `autofunction` can extract all of the text from the docstring when building the docs and this extra info will be there for anyone who is reading the code directly or using an IDE to view the function.  The `ExportDXF` has example code in the docsting as follows:
```
    Example:

        .. code-block:: python

            exporter = ExportDXF(unit=Unit.MM, line_weight=0.5)
            exporter.add_layer("Layer 1", color=ColorIndex.RED, line_type=LineType.DASHED)
            exporter.add_shape(shape_object, layer="Layer 1")
            exporter.write("output.dxf")

```

Lastly, I'm not sure that the description of `_pack2d` is required in the docs as users don't need this info.  Maybe just as a comment in the code? 

Thanks for improving the docs!

**Comment by gumyr** [comment]
Thanks!

**Comment by jdegenstein** [comment]
@roman-dvorak It looks like the SVG assets here https://build123d.readthedocs.io/en/latest/assemblies.html#pack.pack were never added and as a result the links are broken. Could you open another PR and add them?

**Comment by roman-dvorak** [comment]
Thank you for notification. I'm going to check it.

**Pull request merged**
