### PR TITLE
added further initializers to Plane

### PR DESCRIPTION
**Pull request by bernhard-42**
This is not a finished PR, since we should discuss the implementation of Compound (keep it, drop it, change it)
Currently it supports sketches with one single face in order to get the correct direction of this single face. We could also use the underlying workplane of the sketch or drop Compounds

What do you think?

When we have agreed, I'll finish the PR and add tests and streamline class Workplanes (the logic moved to Plane inits now)

### CODE REVIEW

**Comment by bernhard-42** [comment]
Decided to remove Compound from Plane initializers: it is not unique (should i use the workplane location or a singel face location - which could be a different one). If someone wants the workplane location of a compound, `Plane(compound.location)` is the easy solution

**Comment by bernhard-42** [comment]
`Workplanes` is also changed and uses the Plane initializers for `Face` and `Location`

**Comment by gumyr** [comment]
This all looks good to me.  I agree that `Plane(<Compound>)` doesn't need to be supported - BuildSketch is a very special case where the Faces are all on the same plane but that generally isn't true.  Is there anything more that you wanted to do here or is it ready to be merged?

**Comment by bernhard-42** [comment]
Nothing I want to add. Feel free to merge.
Thanks!

**Pull request merged**
