### PR TITLE
don't import from top-level

### PR DESCRIPTION
**Pull request by hiaselhans**
could be related to #26 

changes the imports to use the corresponding sub-packages

### CODE REVIEW

**Comment by jdegenstein** [comment]
I had the best results during testing with `from build123d import Shape` in `jupyter_tools.py` which affects the ipython console in CQ-editor. That being said, I could be wrong about it.

I was having some type checking issues when importing from the sub-packages where `isinstance(obj, Shape)` as returning False unexpectedly.

**Comment by gumyr** [comment]
What is the reason behind not importing from the top level?  The changes seem equivalent to me but I'm missing something important I fear.

Thanks by the way!

**Comment by hiaselhans** [comment]
> I had the best results during testing with `from build123d import Shape` in `jupyter_tools.py` which affects the ipython console in CQ-editor. That being said, I could be wrong about it.
> 
> I was having some type checking issues when importing from the sub-packages where `isinstance(obj, Shape)` as returning False unexpectedly.

That's a very weird bug indeed. With this PR being merged already, how does the latest dev behave in cq-editor? Is there a way we could write a test for it?



> What is the reason behind not importing from the top level? The changes seem equivalent to me but I'm missing something important I fear.
> 
> Thanks by the way!

It's not a hard requirement, but in my opinion it's easier to navigate and it avoids circular imports a bit.
Just thinking about an example module "abmodule" where you have file a defining class A and file b defining class B:

__init__.py:
```python
from abmodule.a import *
from abmodule.b import *
```

a.py:
```python
import B from abmodule
>>>ImportError: cannot import name 'B' from partially initialized module 'abmodule' (most likely due to a circular import)
```

Where `from abmodule.b import B` should still work

**Comment by jdegenstein** [comment]
I just tested again against the latest build123d and (my fork of) CQ-editor and I am NOT seeing that type checking problem. I will keep an eye on it, as I recall the problem was occasionally intermittent.

**Pull request merged**
